navikt/familie-ef-mottak

Dockerfile, app-preprod.yaml, app-prod.yaml, pom.xml, src/main/resources/application-dev.yml, src/main/resources/application.yml
De viktigste endringene fra pipelineSpike branchen -> 
Bygger fat jar (pom.xml) 
setter opp isAlive og påkrevd config
minor changes: expose port i Dockerfile
=> Build fat jar and deploy pipe

.circleci/config.yml, app-prod.yaml, src/main/resources/application-dev.yml, src/main/resources/application.yml
Denne var så og si prod-klar :) Kun litt rydding.
=> Deploy prod

.circleci/config.yml, pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/api/filter/RequestTimeFilter.kt, src/main/kotlin/no/nav/familie/ef/mottak/config/ApplicationConfig.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/MottakServiceImpl.kt, src/main/resources/logback-spring.xml
Id'er og logging, beskrivelse her: https://github.com/navikt/familie-ef-soknad-api/pull/9
I tillegg fjerna jeg slack approval ved deploy (kopiert byggscript fra _soknad-ef-api_)
=> Legg til id'er på requester

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/Application.kt
Oppdater til 2.2.1.RELEASE (org.springframework.boot) og legg til @ConfgurationPropertiesScan
=> Oppdater til 2.2.1.RELEASE (org.springframework.boot)

nais-dev.yaml, nais-prod.yaml
Legg til ingresser som kan brukes fra familie-prosessering
=> Legg til ingresser som kan brukes fra familie-prosessering

src/main/kotlin/no/nav/familie/ef/mottak/integration/ArkivClient.kt
=> Rettet hent saksnummer url

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/mapper/ArkiverDokumentRequestMapper.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/Feltformaterer.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/PdfServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalkerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/Testsøknad.kt
Testet i preprod. Søknad sendt inn med swagger i mottak dukker opp i gosys.
=> Fjer fil fra dokument (bruk siste versjon av kontrakt)

pom.xml, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/SøknadControllerExtension.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/Testsøknad.kt
Oppdater til siste versjon av kontrakt.
+ Gjør kontroller for å hente ut soknad tilgjengelig i test scope. (Kun extension fungerer ikke lenger)
Testet lokalt -> pdf lages og ser ok ut.
Ikke testet i preprod, men regner ikke med at kontraktsendringer skal påvirke annet en det som er testet lokalt (Controller med riktig kontrakt + pdfGenerering)
=> Oppdater til siste versjon av kontrakt. 

pom.xml
Bruk siste versjon av kontrakt.
=> Oppdater kontrakt

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalker.kt, src/test/resources/json/pdf_generated.json
Notere att svaret om man har sendt inn tidligere er en del av søknaden,
```
Lærlingkontrakt
Jeg har sendt inn denne dokumentasjonen til NAV tidligere
Nei
```
Mens listen over vedlegg er plassert til slutt
```
Vedlegg
Vedlegg
Dokumentasjon på utdanningen du skal ta
Dokumentasjon på utdanningen du skal ta
Dokumentasjon på utdanningen du skal ta
```
=> Generer pdf med liste over vedlegg

src/main/kotlin/no/nav/familie/ef/mottak/repository/SoknadRepository.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/TaskMetricRepository.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/FeiletTaskMetric.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/Soknad.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/TaskMetrics.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/TaskMetricService.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/domain/SoknadTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/TaskMetricServiceTest.kt
Vises på https://grafana.adeo.no/d/LbsQz4ZGk/ef-metrikker?orgId=1&refresh=30s&var-datasource=prod-sbs&var-datasourceFss=dev-fss
=> Metrics antall feilet

src/main/kotlin/no/nav/familie/ef/mottak/service/TaskService.kt
Mini - pr. Legg til dokumenttype på task metadata.
=> Test med metadata - dokumenttype.

nais-dev.yaml, nais-prod.yaml
Tmp fix for transaksjons/leaderelection problematikk
=> Pod replicas 1

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/api/filter/RequestTimeFilter.kt, src/main/kotlin/no/nav/familie/ef/mottak/config/NaisProxyCustomizer.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/Testdata.kt, src/test/resources/json/pdf_generated_barnetilsyn.json
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-1876
=> Oppdatert kontrakter - Fjernet dokumentasjon for tidligere fakturaer

src/main/kotlin/no/nav/familie/ef/mottak/config/KafkaErrorHandler.kt
Buggen gjorde at Kafkalytter ble restartet umiddelbart, noe som kastet feil i errorHandler.
=> Fikset bug i errorHandler

src/test/kotlin/ApplicationLocal.kt, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/MockConfiguration.kt
Legger til dette slik tasks blir prosessert og at vi sender videre søknaden til sak
=> Mock klienter slik det er mulig å sende en innkommende søknad til sak

src/main/kotlin/no/nav/familie/ef/mottak/repository/DokumentasjonsbehovRepository.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/Dokumentasjonsbehov.kt, src/main/resources/db/migration/V11__dokumentasjonsbehov.sql
Dokumentasjonsbehov skal sendes i beskjed til ditt nav og vises frem i egen visning.
=> Ny tabell for å lagre dokumentasjonsbehov

src/main/kotlin/no/nav/familie/ef/mottak/service/ScheduledEventService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/TaskService.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/LagJournalføringsoppgaveTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTask.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/TaskServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/LagJournalføringsoppgaveTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTaskTest.kt
Vi ønsker å sende en "vi har mottatt søknad" til alle. 
Vi ønsker å sende "dokumentasjonsbehov" melding der det er behov for det. 
To meldinger
=> Melding ditt nav mottatt søknad

README.md, pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/config/ApplicationConfig.kt
Swagger etter dependabot oppdateringer trenger litt hjelp.
=> Swagger config.

src/main/resources/application-dev.yml, src/main/resources/application-local.yml
Bytter ingress i ef-maler nå. Testet i preprod. Fungerer. Pdf lages og sendes til gosys.
=> dev-adeo -> dev.intern.nav.no

src/main/kotlin/no/nav/familie/ef/mottak/integration/IntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/ArkiveringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SakService.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/FerdigstillJournalføringTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/LagJournalføringsoppgaveTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/OpprettSakTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTask.kt, src/test/kotlin/no/nav/familie/ef/mottak/integration/IntegrasjonerClientTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SakServiceTest.kt
Lagt til to nye tasker. En som oppretter sak i Infotrygd om det ikke finnes noen sak på søker fra før, og en som ferdigstiller journalposten.
=> Automatisk journalføring

Dockerfile
https://nav-it.slack.com/archives/CJN0STWB0/p1612387453141300
=> Nais kjører ikke lengre appene med root og RUN chmod crasher

src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalfoeringHendelse.kt, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalfoeringHendelseDbUtil.kt, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseService.kt, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalpostUtil.kt, src/test/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseServiceTest.kt
Hadde et ønske om å lage hjelpemetoder i Journalpost-klassen, men siden den er på et fellesprosjekt så lurte jeg på om klassen burde utvides der, eller om man bare oppretter egen klasse (som jeg valgte å kalle JournalpostUtil) i stedet?
=> Refaktorering: Slanket JournalhendelseService-klassen

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/integration/InfotrygdReplikaClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/integration/IntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/integration/health/FamilieIntegrasjonHealth.kt, src/main/kotlin/no/nav/familie/ef/mottak/integration/health/InfotrygdReplikaHealth.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/InfotrygdService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SakService.kt, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/mottak/service/SakServiceTest.kt
Avhengig av https://github.com/navikt/familie-integrasjoner/pull/328
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3893
=> Sjekker om person finnes i infotrygd og logger dette

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/mapper/OpprettOppgaveMapper.kt, src/main/kotlin/no/nav/familie/ef/mottak/mapper/SøknadMapper.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/Søknad.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceImpl.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/LagBehandleSakOppgaveTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/LagJournalføringsoppgaveTask.kt, src/main/resources/db/migration/V14__behandle_i_ny_saksbehandling.sql, src/main/resources/db/migration/V14__skal_automatisk_journalfores.sql, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/LagBehandleSakOppgaveTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/LagJournalføringsoppgaveTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/util/DomainTestUtil.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4347
CoAuthor @neringaalt 
Når denne merges kan https://unleash.nais.io/#/features/strategies/familie.ef.soknad.visSkalIkkeJournalfores settes til enabled
=> Lagt til flagg for behandling i ny saksbehandling

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
Github skal fase ut deres (docker) "Package Registry (GPR)" til fordel for deres "GitHub Container Registry (GHCR)".
https://nav-it.slack.com/archives/C01DE3M9YBV/p1613039240045100
=> Tar i bruk ghcr

src/main/kotlin/no/nav/familie/ef/mottak/mapper/BehandlesAvApplikasjon.kt, src/main/kotlin/no/nav/familie/ef/mottak/mapper/OpprettOppgaveMapper.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/mottak/mapper/OpprettOppgaveMapperTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/util/TestContants.kt
Etter funk testing av 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-3707
=> Fjerner url til ny løsning fra oppgaver etter diskusjon med Mirja

pom.xml
Vil oppdatere: 
Sonar-maven
token-validation
Kotlin
felles
Bump wiremock
Bump kotlinx-coroutines-core
Kontrakter
Prosessering
Testet innsending virker og sak dukker opp i ef-sak for søker
=> Dependabot samlebranch oppdatering

.github/workflows/deploy-dev.yml
Deploy mottak til preprod med workflow_dispatch
=> Deploy til preprod med workflow_dispatch

pom.xml
for å bedre håndtere optimistic lock exception
=> Oppdatererer prosessering

pom.xml
Kontrakter -> 2.0_20210625133148_3b67468
Bump token-validation.version from 1.3.7 to 1.3.8  dependencies
Bump spring-boot-starter-parent from 2.5.1 to 2.5.2  dependencies
Bump kotlin.version from 1.5.10 to 1.5.20  dependencies
test i preprod = ok.
=> Dependabot samlet

nais-dev.yaml, nais-prod.yaml, pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/api/DokumentasjonsbehovController.kt, src/main/kotlin/no/nav/familie/ef/mottak/api/SkjemaController.kt, src/main/kotlin/no/nav/familie/ef/mottak/api/SøknadController.kt, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
Må merges etter https://github.com/navikt/familie-ef-mottak/pull/415
=> Lagt til søtte for tokenx

src/main/kotlin/no/nav/familie/ef/mottak/api/EttersendingController.kt, src/main/kotlin/no/nav/familie/ef/mottak/api/SøknadController.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/EttersendingService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadService.kt, src/main/resources/application.yml, src/test/kotlin/ApplicationLocal.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/DokumentasjonsbehovControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/EttersendingControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/SøknadControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseKafkaHåndtererTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/MockFamilieDokumentClient.kt, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/MockUtil.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/EttersendingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/JournalføringsoppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceIntegrasjonTest.kt, src/test/resources/application-local.yml
Burde merges etter https://github.com/navikt/familie-ef-soknad-api/pull/507
=> Fjern deprecated innsending

.github/workflows/integrasjonsTest.yml
La også til cache
Liker nå mer den i ef-sak, https://github.com/navikt/familie-ef-sak/blob/master/.github/workflows/build-dev.yml
=> Bygger dependabot PR's uten sonar

src/main/kotlin/no/nav/familie/ef/mottak/mapper/OpprettOppgaveMapper.kt
https://jira.adeo.no/browse/FAGSYSTEM-183272
=> Bruk nav enhet fra journalpost ved opprettelse av journalføringsoppgave

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/api/EttersendingController.kt, src/main/kotlin/no/nav/familie/ef/mottak/mapper/EttersendingMapper.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/EttersendingService.kt, src/main/resources/db/migration/V20__slette_innhold_i_ettersendingstabell.sql, src/test/kotlin/no/nav/familie/ef/mottak/api/EttersendingControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/EttersendingRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/EttersendingServiceTest.kt
Kjører SNAPSHOT-versjon mot kontrakter frem til kontrakter er godkjent.
=> Endret modell for ettersending

src/main/kotlin/no/nav/familie/ef/mottak/mapper/ArkiverDokumentRequestMapper.kt
Bedre navngiving av dokument: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-5974
=> Rettet tittel på dokument som blir arkivert

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/603
- https://github.com/navikt/familie-ef-mottak/pull/602
- https://github.com/navikt/familie-ef-mottak/pull/601
=> Dependabot oppdateringer 20210927-123924

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalker.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalkerTest.kt, src/test/resources/json/pdf_generated_barnetilsyn.json, src/test/resources/json/pdf_generated_overgangsstønad.json, src/test/resources/json/pdf_generated_skolepenger.json
Overskrifter i pdf skal nå være: 
"Søknad om overgangsstønad, 15-00.01"
"Søknad om stønad til barnetilsyn, 15-00.02"
"Søknad om stønad til skolepenger, 15-00.04"
=> Bedre overskrifter pdf.

nais-prod.yaml
https://nav-it.slack.com/archives/GREQVPXHS/p1639144876082100?thread_ts=1638365764.078500&cid=GREQVPXHS
=> db-n1-standard-1 er ikke søttet som tier, må bruke custom

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/integrasjonsTest.yml
Tar i bruk cache fra setup-java.
Tar i bruk fetch-depth for sonar
=> Endrer til å bruke major versjons av checkout og java.

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/679
- https://github.com/navikt/familie-ef-mottak/pull/676
- https://github.com/navikt/familie-ef-mottak/pull/671
=> Dependabot oppdateringer 20220103-125531

src/main/resources/application-dev.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7659
=> Skrur om integrasjoner mot q1 i dev

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/693
- https://github.com/navikt/familie-ef-mottak/pull/692
- https://github.com/navikt/familie-ef-mottak/pull/691
=> Dependabot oppdateringer 20220124-083059

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/integrasjonsTest.yml, pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/708
- https://github.com/navikt/familie-ef-mottak/pull/707
- https://github.com/navikt/familie-ef-mottak/pull/706
=> Dependabot oppdateringer 20220307-083843

pom.xml, src/test/kotlin/no/nav/familie/ef/mottak/IntegrasjonSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/DokumentasjonsbehovControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/EttersendingControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/SøknadControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/DokumentasjonsbehovRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/EttersendingRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/HendelsesloggRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/StatistikkRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/SøknadRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/TaskRepositoryUtvidetTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/VedleggRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/DbMigreringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/TaskMetricServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/util/DbContainerInitializer.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8357
=> Tatt i bruk testcontainer for å få en postgresdatabase å teste med

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/730
- https://github.com/navikt/familie-ef-mottak/pull/729
- https://github.com/navikt/familie-ef-mottak/pull/728
- https://github.com/navikt/familie-ef-mottak/pull/726
=> Dependabot oppdateringer 20220404-082255

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/integrasjonsTest.yml, pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/740
- https://github.com/navikt/familie-ef-mottak/pull/739
- https://github.com/navikt/familie-ef-mottak/pull/738
- https://github.com/navikt/familie-ef-mottak/pull/737
- https://github.com/navikt/familie-ef-mottak/pull/735
- https://github.com/navikt/familie-ef-mottak/pull/734
- https://github.com/navikt/familie-ef-mottak/pull/732
=> Dependabot oppdateringer 20220419-084401

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/746
- https://github.com/navikt/familie-ef-mottak/pull/744
=> Dependabot oppdateringer 20220425-082227

src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt
Selv om behandlesAvApplikasjon er satt til INFOTRYGD skal oppgaven plasseres i mappe, da disse vil bli migrert fra vår løsning. For barnetilsyn og skolepenger vil vi fortsatt sjekke hva behandlesAvApplikasjon er satt til
=> Vil plassere alle oppgaver for overgangsstønad i mappe

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/config/DatabaseConfiguration.kt
Deployer i dev
* https://github.com/navikt/familie-ef-mottak/actions/runs/2239055739
=> Oppdaterer pom for å trigge build

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadService.kt
Setter derfor skalBehandlesINyLøsning=true for at oppgave skal kunne plukkes fra vår oppgavebenk.
**Før merging**
=> Vil ikke automatisk journalføre barnetilsyn.

src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt
Vil plassere journalføringoppgaver for barnetilsyn i mappe EF-sak 65 - Opplæring
=> Opplæringsmappe barnetilsyn

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalpostUtil.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/JournalføringsoppgaveService.kt
1.7.0 - krever "exhaustive" when. Prøvd å fikse det uten å endre funksjonalitet for mye.
=> Kotlin versjon when

src/test/kotlin/no/nav/familie/ef/mottak/mapper/ArkiverDokumentRequestMapperTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-8375
=> Forbedring av mappertest, har en test som sjekker alle felter

src/main/kotlin/no/nav/familie/ef/mottak/repository/SøknadRepository.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadService.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/SøknadRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceTest.kt
https://nav-it.slack.com/archives/C01087QRJ2U/p1656332711415859
=> Henter dokumentasjonsbehov for siste stønaden av hver stønadstype

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/840
- https://github.com/navikt/familie-ef-mottak/pull/837
- https://github.com/navikt/familie-ef-mottak/pull/836
- https://github.com/navikt/familie-ef-mottak/pull/833
- https://github.com/navikt/familie-ef-mottak/pull/829
- https://github.com/navikt/familie-ef-mottak/pull/828
- https://github.com/navikt/familie-ef-mottak/pull/825
=> Dependabot oppdateringer 20220825-083114

pom.xml
\nErstatter:
- https://github.com/navikt/familie-ef-mottak/pull/868
- https://github.com/navikt/familie-ef-mottak/pull/863
- https://github.com/navikt/familie-ef-mottak/pull/862
- https://github.com/navikt/familie-ef-mottak/pull/857
- https://github.com/navikt/familie-ef-mottak/pull/851
=> Dependabot oppdateringer 20220926-123841

src/main/kotlin/no/nav/familie/ef/mottak/mapper/OpprettOppgaveMapper.kt
https://nav-it.slack.com/archives/C03V59GMEQZ/p1667401655711939?thread_ts=1667396324.423949&cid=C03V59GMEQZ
=> Matcher klage hvis brevkode er NAV 90-00.08

src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseKafkaListener.kt, src/main/resources/application-dev.yml
Kjørte en deploy igår med seekaware (se commits)
=> Kafka topic journalpost q1

pom.xml, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalkerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/Testdata.kt, src/test/resources/json/pdf_generated_barnetilsyn.json, src/test/resources/json/pdf_generated_overgangsstønad.json, src/test/resources/json/pdf_generated_skolepenger.json
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10347
=> Oppdaterer kontrakter med opplysninger om adresse

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/service/AutomatiskJournalføringService.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/AutomatiskJournalføringServiceTest.kt
- Oppretter oppgave async
https://github.com/navikt/familie-kontrakter/pull/696
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10672
=> Fjernet behandleSakOppgaveId fra AutomatiskJournalføringResponse

README.md, src/main/resources/application-dev.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10604
=> Tar i bruk q2

src/main/resources/application-dev.yml
Ref endring i ettersending: https://github.com/navikt/familie-ef-ettersending/pull/554
=> Gammel ingress skal ikke lenger brukes

.github/workflows/deploy-dev.yml, src/main/kotlin/no/nav/familie/ef/mottak/repository/SøknadRepository.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/EttersendingService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadService.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/util/DittNavUtil.kt, src/main/kotlin/no/nav/familie/ef/mottak/util/VedleggUtils.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTaskTest.kt
Skal opprette en task som sender søker en påminnelse om å sende inn ettersending etter innsendelse av søknad. Beskjeden skal sendes etter tre dager eller første virkedag etter dette.
- Tasken skal kun opprettes dersom søknaden inneholder ikke innsendte dokumentasjonsbehov
- Når tasken trigges sjekker den om det er sendt inn en søknad i ettertid, den sjekker også om det er sendt inn ettersending i ettertid. Dersom dette er tilfellet skal den ikke sende en påminnelse til bruker
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-2204)
=> Oppfølgingsmelding ditt nav

src/main/kotlin/no/nav/familie/ef/mottak/service/DittNavKafkaProducer.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTask.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTaskTest.kt
=> kjørt ktlint

src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/AutomatiskJournalføringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt
Hvorfor: 
Toggle er skrudd på  i dev og prod - trenger ikke denne lenger.
=> Vil slette toggle. Enablet i prod og dev.

pom.xml
Hvorfor? 
Samlebranch - dependabot. Oppdateringer av dependencies.
=> Oppdater dependencies

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
=> Permission write

pom.xml
Vil oppdatere 
felles.version
kontrakter.version
token-validation.version
Tester i preprod før merge.
=> Oppdater avhengigheter.

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-unleash-api-token.yaml
Vil slutte å bruke NAIS_DEPLOY_APIKEY. 
Har autorisert app i console og testet i preprod
https://console.nav.cloud.nais.io/team/teamfamilie/repositories
Samme som denne: 
https://github.com/navikt/familie-ef-sak/pull/2496
=> Vil deploye uten å bruke NAIS_DEPLOY_APIKEY.

pom.xml
SKal oppdatere prosessering for å ta ibruk nytt endepunkt for uthenting av status
=> Oppdatere prosessering

.github/dependabot.yml
Vil bytte ut PAT med READER_TOKEN
=> Vil bruke READER_TOKEN

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/config/ApplicationConfig.kt, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/test/kotlin/no/nav/familie/ef/mottak/IntegrasjonSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/EttersendingControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/SøknadControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/MockController.kt, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/MockFamilieDokumentClient.kt, src/test/resources/application-integrationtest.yml
Fikk ikke startet lokalt i main koden, så har ikke gjort noe her. Det blir dessuten litt vanskelig å få det til å virke sammen med ef-sak da ef-sak ikke kan bumpes til nyeste versjon av spring enda heller.
Går ut ifra at mottak ikke brukes veldig mye i lokal utvikling, og at det derfor går fint å merge dette.
=> Oppgraderer til tokens-support 4

.github/workflows/delete_packages.yml
Legg til workflow for å slette gamle images:
´0 2-5 * * *´ means "At 00 minutes past the hour, at 2 AM, 3 AM, 4 AM, and 5 AM, every day".
=> Legg til workflow for å slette gamle images:

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, pom.xml
GHCR ga problemer med håndtering av image, og nais-teamet jobbet derfor med alternativ løsning. Løsningen ble GAR og det er dermed anbefalt å migrere over for en bedre brukeropplevelse.
https://nav-it.slack.com/archives/C5KUST8N6/p1678189735336849?thread_ts=1678188149.218519&cid=C5KUST8N6
https://docs.nais.io/build/how-to/oci-migration/
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-21284)
Legger også til generering av byosbom for å vise dependency graph i salsa og nais console: https://doc.nais.io/services/salsa/
=> Migrerer til gar

.github/workflows/deploy-prod.yml
Deploy til prod feiler - rettet i permissions
=> Fix permissions

src/test/resources/application-local.yml
Vi ønsker å legge til fakedings for å kunne kjøre applikasjonen lokalt
=> Bruke fakedings lokalt

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapper.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadskvitteringService.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapperTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/Testdata.kt, src/test/resources/json/pdf_generated_overgangsstønad.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer.json
Beskrivelse:
Vi ønsker å ha en måte å skille hvordan enkelte deler av pdf-kvitteringen skal se ut og at det skal sende med informasjon fra søknaden.
Løsning:
Lagt til en type i feltlisteMap med tabell barn
=> Legge til type til feltListMap

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapper.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapperTest.kt, src/test/resources/json/pdf_generated_barnetilsyn_med_typer.json, src/test/resources/json/pdf_generated_ettersending_med_typer.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer.json, src/test/resources/json/pdf_generated_skolepenger_med_typer.json
Beskrivelse:
Vi ønsker å ha en måte å skille hvordan enkelte deler av pdf-kvitteringen skal se ut og at det skal sende med informasjon fra søknaden.
Løsning:
Lagt til en Vedleggs type i feltlisteMap
=> legg til vedlegg som VisningsVariant

.deploy/nais-dev.yaml, src/main/kotlin/no/nav/familie/ef/mottak/api/PdfSøknadController.kt, src/main/kotlin/no/nav/familie/ef/mottak/integration/PdfKvitteringClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/integration/PdfKvitteringConfig.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/PdfKvitteringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/PdfSøknadService.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/mottak/service/PdfKvitteringServiceTest.kt
- La på dev-url
- Endret navn fra iText
=> Nytt navn og la på dev-url

src/main/kotlin/no/nav/familie/ef/mottak/service/PdfKvitteringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapper.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapperTest.kt, src/test/resources/json/pdf_generated_barnetilsyn_med_typer.json, src/test/resources/json/pdf_generated_ettersending_med_typer.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer.json, src/test/resources/json/pdf_generated_skolepenger_med_typer.json
- Bruker vår mapper som legger på visningsvariant for å få tabell for barn i pdf-en
- Endret Visningsvariant til kotlins enum konvensjon: https://kotlinlang.org/docs/enum-classes.html#working-with-enum-constants
=> Endrett navn på visningsvariant: enum verdi

src/main/kotlin/no/nav/familie/ef/mottak/service/PdfKvitteringService.kt
Denne skal være SøknadTilGenereltFormatMapper ettersom SøknadTreeWalker er ef sin nåværende funskjon
=> Bug bytte ut SøknadTreeWalker med SøknadTilGenereltFormatMapper

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapper.kt, src/test/resources/json/pdf_generated_barnetilsyn_med_typer.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer.json
Lagt på visningsvariant for arbeidsforhold-tabell
=> Visningsvariant på arbeidsforhold

.deploy/nais-prod.yaml
Trenger outbound access policy mot familie-pdf i prod
=> Kan nå familie-pdf i prod

src/main/kotlin/no/nav/familie/ef/mottak/api/StatusController.kt
Vil logge mindre aggressivt ved lite bruk av søknadsdialog.
=> Vil logge mindre aggressivt ved lite bruk av søknadsdialog.

pom.xml, src/test/kotlin/no/nav/familie/ef/mottak/api/SøknadControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceIntegrasjonTest.kt
Bumper kontrakter og legger ved locale på alle "SøknadMedVedlegg"
=> Bumper kontrakter versjon

src/main/kotlin/no/nav/familie/ef/mottak/integration/PdfKvitteringClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/FeltMap.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadskvitteringService.kt, src/test/resources/json/pdf_generated_barnetilsyn.json, src/test/resources/json/pdf_generated_barnetilsyn_med_typer_ny.json, src/test/resources/json/pdf_generated_ettersending.json, src/test/resources/json/pdf_generated_ettersending_med_typer.json, src/test/resources/json/pdf_generated_overgangsstønad.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer_ny.json, src/test/resources/json/pdf_generated_skolepenger.json, src/test/resources/json/pdf_generated_skolepenger_med_typer.json
Sender med språk i PdfConfig dersom den finnes i innsendingsdetaljer, eller "nb" dersom den ikke finnes
=> Språk i pdfconfig

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt
Vedlegg sendes ikke inn til finnFelter men har en egen mapper
=> Fjern veglegg-sjekk i finnFelter funksjonen

src/main/kotlin/no/nav/familie/ef/mottak/api/PersonController.kt, src/main/kotlin/no/nav/familie/ef/mottak/api/SkjemaController.kt, src/main/kotlin/no/nav/familie/ef/mottak/api/SøknadController.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/ArkiveringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/FeltformatererPdfKvittering.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/MappeService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadskvitteringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/AutomatiskJournalførTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SøknadsreduksjonTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SøknadsslettingTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/VelgAutomatiskEllerManuellFlytTask.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/ArkiveringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/MappeServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadskvitteringServiceIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadskvitteringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/AutomatiskJournalførTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/FerdigstillJournalføringTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/VelgAutomatiskEllerManuellFlytTaskTest.kt
@marcuasc jobber med ´lagre skjema for arbeidssøker´i en egen pr så har kommentert ut testen
=> Lagre ned dokumentasjonsbehov ny flyt

src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/FeltMap.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMapTest.kt, src/test/resources/json/pdf_generated_barnetilsyn.json, src/test/resources/json/pdf_generated_barnetilsyn_med_typer_ny.json, src/test/resources/json/pdf_generated_ettersending.json, src/test/resources/json/pdf_generated_ettersending_med_typer.json, src/test/resources/json/pdf_generated_overgangsstønad.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer_ny.json, src/test/resources/json/pdf_generated_skolepenger.json, src/test/resources/json/pdf_generated_skolepenger_med_typer.json
Endret:
nå skal det stå `Skjemanummer: NAV 15.08.01`, slik at skjermlesere lettere kan forstå hva `NAV 15.08.01` betyr
Både norsk og engelsk. 
Application number
=> Legge til skjemanummer som type i feltmap

src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
Lagt til config for familie-pdf
=> Client credentials for familie-pdf

src/main/kotlin/no/nav/familie/ef/mottak/api/SøknadController.kt
Oppdatere GetMapping for henting av sist innsendte søknader.
=> Oppdatere GetMapping for henting av sist innsendte søknader.

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/test/resources/json/pdf_generated_overgangsstønad_med_typer_ny.json
Testet i preprod: [UtenFødselsdatoPåEksisterendeBarn.pdf](https://github.com/user-attachments/files/18687263/UtenFodselsdatoPaEksisterendeBarn.pdf)
=> Viser ikke fødselsdato på barn hvis det er født

src/main/kotlin/no/nav/familie/ef/mottak/integration/PdfKvitteringClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadsfeltType.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMapTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/Testdata.kt, src/test/resources/json/pdf_generated_barnetilsyn_med_typer_ny.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer_ny.json, src/test/resources/json/pdf_generated_skolepenger_med_typer_ny.json
[Søknad om overgangsstønad - enslig mor eller far (2).pdf](https://github.com/user-attachments/files/18659757/Soknad.om.overgangsstonad.-.enslig.mor.eller.far.2.pdf)
=> Utenlandsopphold har tabell-format

pom.xml, src/test/kotlin/no/nav/familie/ef/mottak/service/Testdata.kt
Ønsker å ha med endre rekkefølgen i aktiviteter 
Formaterte testfilen  😅  derfor er det litt mange linjer som endres.  Men la også til navn under aktiviteter
=> oppdater kontrakter

src/main/kotlin/no/nav/familie/ef/mottak/service/PdfService.kt
Logger ut for kun en spesifikk task som feiler i prod.
=> Logger ut innholdet i en søknad for å se om det er en karakter som ikke finnes i tegnsett

src/main/kotlin/no/nav/familie/ef/mottak/service/PdfService.kt
Dette er nå løst og debug-loggingen kan fjernes.
=> Fjerner logging for en spesifikk søknad som hadde en feil i prod. 

.deploy/nais-prod.yaml, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/Søknad.kt, src/main/resources/db/migration/V25__json_soknad_opprydding.sql
Testet - sendt inn søknad = alt ok
https://ensligmorellerfar.ansatt.dev.nav.no/behandling/f3a9841e-a278-464c-9f65-fe296532f033
=> Soknad json opprydding
