src/main/kotlin/no/nav/familie/ef/mottak/service/SakService.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SakServiceTest.kt
Ettersom behandlingstema kun finnes på "våre" journalposter forsøker vi heller å se på brevkode i dokumentene. Her vil treffraten være vesentlig bedre for saker opprettet i perioden 2019-medio 2020. Før 2019 er det nok også litt "ymse", men ikke sikkert det er like kritisk
=> Skal kun opprette sak for førstegangsbehandlinger for hver stønad

src/main/kotlin/no/nav/familie/ef/mottak/integration/IntegrasjonerClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/mapper/OpprettOppgaveMapper.kt, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/MockConfiguration.kt
Bumper opprett oppgave til v4 og opprett oppgave til v2, så vi kan fjerne disse endepunktene i familie-integrasjoner.
"finn oppgaver" har blitt en post, men request / response er likt.
"opprett oppgave" har ny request: OpprettOppgaveRequest.
ferdigstilling benyttet "opprett oppgave"-path, må bruke sin egen etter endring av path.
Fant noen funksjoner i IntegrasjonerClient uten parametre - disse er gjort om til verdier på lik linje med de andre.
=> Bump "opprett oppgave" til v2 og bump "finn oppgaver" til v4

pom.xml
Bump token-validation.version from 1.3.3 to 1.3.5 #483
Bump unleash-client-java from 3.3.4 to 4.2.1
Bump confluent.version from 6.1.0 to 6.1.1
Bump kotlin.version from 1.4.31 to 1.4.32
Bump mockk from 1.10.6 to 1.11.0
Bump spring-cloud.version from 3.0.1 to 3.0.2
Bump avro-maven-plugin from 1.10.1 to 1.10.2
Bump spring-boot-starter-parent from 2.4.3 to 2.4.4
Bump avro from 1.10.1 to 1.10.2
=> Dependabot samlet:

src/main/kotlin/no/nav/familie/ef/mottak/task/HentSaksnummerFraJoarkTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SjekkOmJournalpostHarFåttEnSak.kt
Vi riskierer att en task feiler kl 16, blir satt til feilet, kl 06 blir den rekjørt og FEILET på nytt. Så kl 7 blir den satt til KLAR_TIL_PLUKK, så vi får aldri fanget den opp fordi den ikke ligger i "FEILET", men klar til plukk. Så blir den rekjørt senere kl 16.30 på nytt, når vi ikker er på jobb. Så den er satt til FEILET mellom 16.30-06.00
=> Setter manuell oppfølning på tasker som rekjører langt frem i tid.

pom.xml
Sjekket at alt er ok i preprod: 
Bump spring-boot-starter-parent from 2.5.2 to 2.5.3
Bump wiremock-jre8 from 2.28.1 to 2.29.1
Bump kotlin.version from 1.5.10 to 1.5.20  dependencies
Bump kotlinx-coroutines-core from 1.5.0-native-mt to 1.5.1-native-mt
Bump mockk from 1.11.0 to 1.12.0
=> Dependabot 2 august

src/main/resources/application.yml
Ref https://github.com/navikt/familie-ef-maler/pull/11
familie-ef-maler i fss i prod i default namespace kan slettes etter denne merge (når det er verifisert att det virker)
=> Tar i bruk dokgen i gcp i prod

src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt
0389 er nedlagt. Dette er kode som skal fjernes etter at en oppgave i mottak er kjørt.
=> Vil lage oppgave på ENHEN-NAY ("4489") hvis enhet er 0389 

src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseKafkaListener.kt
FeatureToggle er opprettet i unleash og er aktivert: https://unleash.nais.io/#/features/strategies/familie.ef.mottak.kafka.onprem 
Denne skal deaktiveres ved overgang til gcp.
=> Featuretoggle kafka listener som skal brukes ved overgang til prod

src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalfoeringHendelse.kt, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalfoeringHendelseDbUtil.kt, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseKafkaHåndterer.kt, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseKafkaListener.kt, src/main/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseService.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/HendelsesloggRepository.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseKafkaHåndtererTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/hendelse/JournalhendelseServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/repository/HendelsesloggRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/util/DomainTestUtil.kt
Testet med noen søknader i dev, og det ser ut til å virke. Det var en endring i data på topic i aiven, og det er endring i joark mapping. Forskjellene er dokumentert her: https://confluence.adeo.no/pages/viewpage.action?pageId=432217859
auto-offset-reset er satt til latest - så den skal hente siste melding på topic første gangen. Med tanke på den korte nedetiden ved deploy, skal det kunne leses fra slutten av topic
Offset er ikke i sync mellom on-prem og gcp, så sikkerhetsmekanismen med å ikke prosessere samme hendelse flere ganger, er gjort om til å ta utgangspunkt i hendelseId fremfor offset.
=> Overgang til aiven

src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTaskTest.kt
Fjerner bruk av: familie.ef.mottak.melding-ditt-nav-til-ef-ettersending
=> Fjern toggles som ikke lenger brukes (enablet i alle miljøer)

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/integration/SaksbehandlingClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/AutomatiskJournalføringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/AutomatiskJournalførTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/TaskFlyt.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/AutomatiskJournalføringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/AutomatiskJournalførTaskTest.kt
Vil automatisk journalføre digitale søknader - opprette førstegangs-søknad-behandling og behandle sak oppgave.
Dersom "noe" går galt når vi journalfører bruker vi fallback "manuell" journalføring. 
Valg vi har tatt: 
Vi er defensive - alle feil, eller ressurs uten data vil gjøre at vi går tilbake til manuell flyt.
=> Automatisk journalføring taskimpl

pom.xml, src/test/kotlin/no/nav/familie/ef/mottak/service/Testdata.kt, src/test/resources/json/pdf_generated_barnetilsyn.json, src/test/resources/json/pdf_generated_overgangsstønad.json, src/test/resources/json/pdf_generated_skolepenger.json
[FAVRO](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12261)
Trenger å bumpe versjonen av kontrakter slik at den tar inn de nye feltene `oppholdsland` i medlemskap og `land` i utenlandsopphold. 
- ef-soknad [PR 1245](https://github.com/navikt/familie-ef-soknad/pull/1245) (Lagt til de nye feltene)
- ef-soknad-api [PR 844](https://github.com/navikt/familie-ef-soknad-api/pull/844) (mapper de nye feltene)
- ef-sak PR (legger til de nye feltene i søknadsdata)
- familie-kontrakter [PR 744](https://github.com/navikt/familie-kontrakter/pull/774) (legger til oppholdsland i medlemskap og land i utenlandsopphold) og [PR 746](https://github.com/navikt/familie-kontrakter/pull/776) (gi mulighet til å sette de nye feltene i `TestSøknadsBuilder`)
=> Bump kontrakter-versjon

pom.xml
Hvorfor? 
Vil oppdatere 5 dependecies. 
Vil fjerne httpclient. 
Testet? Har deployet og sendt inn en søknad i preprod. Alt ok.
Oppdaterer disse: 
<artifactId>spring-boot-starter-parent</artifactId>
<version>3.1.0</version>
<kotlin.version>1.8.22</kotlin.version>
<token-validation.version>3.1.0</token-validation.version>
<artifactId>postgresql</artifactId>
<version>1.18.3</version>
<artifactId>maven-assembly-plugin</artifactId>
<version>3.5.0</version>
=> Dependabot samleoppdateringer + fjernet httpclient.

nais-dev.yaml, nais-prod.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver godt hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
=> Fjern CPU-limit

src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt
Hvorfor: trenger ikke denne toggelen lenger.
=> Vil slette toggle. Enablet i prod og dev.

nais-dev.yaml, nais-prod.yaml, pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/service/EttersendingService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/FjernProsessertDataScheduledEventService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/OpprettTaskScheduler.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/TaskMetricService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/TaskProsesseringService.kt, src/main/resources/application-dev.yml, src/test/kotlin/no/nav/familie/ef/mottak/service/EttersendingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceTest.kt
**Hvorfor:** Vil gjerne kjøre med mer enn en pod i mottak for ikke få nedetid ved f.eks oom feil. 
**Derfor** : Øker min pods replica til 2. 
**Da må vi også:** 
Hvis vi skal kjøre med mer enn en pod uten å få duplikate tasks, eller feil pga samtidige kall mot db må vi: 
* Fjerne @Scheduled for opprettelse av task gitt nye kolonner i søknadstabell. (skjema, søknader og ettersendinger)
* Legge på leader-selection og bruke leader for å rydde i database og oppdatere metrikker. 
Har testet innsending av OS-søknad og vil teste innsending av BT- og SPsøknad samt innsending av arbeidssøkerskjema og ettersendinger før merging til prod.
=> Mottak - flere podder

src/main/kotlin/no/nav/familie/ef/mottak/api/ForvaltningController.kt, src/main/kotlin/no/nav/familie/ef/mottak/config/ApplicationConfig.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/EttersendingService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/TaskProsesseringService.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/EttersendingServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/TaskProsesseringServiceTest.kt
Vi bruker fortsatt @Scheduled for å opprette task ved innsending av ettersending. 
Ønsker å opprette task i mottak ved innsending av ettersending på samme måte som søknader. 
For at dette skal fungere må alle tasks få unik callId. Det opprettes en task pr stønadstype. 
Ønsker å gjenbruke callId vi har + stønadstype i task.
=> Vil opprette callId pr stønadstype på ettersendingstasks

src/test/kotlin/no/nav/familie/ef/mottak/service/AutomatiskJournalføringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt
Tester feiler nå som vi har kommet fram til 2024. Testen bruker ellers "nå", så bytter til "nå" også for år.
=> Fiks testfeil som har oppstått pga. nytt år (2023->2024)

src/main/kotlin/no/nav/familie/ef/mottak/api/StatusController.kt
Vil minimere falske alarmer og logge warning og feil. Logger kun feil på dagtid. 
Hvis mellom 12:00 og 21 flagger vi gult dersom det er mer enn 12 timer siden vi fikk inn en søknad. 
Vi flagger gult hvis natt og 24t
Vi logger warning dersom vi ikke har fått inn søknad de siste 15 minuttene og det er dagtid (08:00->22:00).
Vi logger error dersom vi ikke får inn søknad på tre timer (dagtid). 
Vi kan vurdere å flagge rødt (DOWN) senere.
=> Status v2 mindre gult

src/main/kotlin/no/nav/familie/ef/mottak/api/StatusController.kt
Vi fikk litt mange error/warnings/info i loggen denne helga. 
Vil ikke logge warning/error når det er helg.
Fjerner info logg
Øker warning fra 15 til 20 min uten søknad.
Dersom det går 12 timer uten søknad vil vi uansett flagge rødt til status.
=> Vil ikke logge warning/error når det er helg.

src/main/kotlin/no/nav/familie/ef/mottak/config/KafkaConfig.kt, src/main/resources/application.yml, src/test/resources/application-integrationtest.yml, src/test/resources/application-local.yml
Fix deprecated metode.
Forsøker å forbedre lesbarhet ved å legge all kafka-config for listeners på ett sted, hvis dere er enige at denne måten er bedre? Tenker det kan være greit å ha dette som felles måte og skrive kafka config for listeners på, for i andre apper som har flere listeners må man uansett ha en egen kafka-config utover det som er i `application.yml`
Testet at hendelser leses i preprod med denne configen.
=> Oppdaterer kafka config

src/main/kotlin/no/nav/familie/ef/mottak/integration/PdfClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/integration/PdfKvitteringClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/repository/domain/FeltMap.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/Feltformaterer.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/PdfKvitteringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/PdfService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalker.kt, src/test/kotlin/no/nav/familie/ef/mottak/mockapi/MockConfiguration.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/FeltformatererTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMapTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalkerTest.kt
Slipper å bruke:
```
Map<String, Any>
Map<String, *>
List<*>
List<Map<String, *>>
```
og mye annet mindre leselig
=> Typedefinert felt map

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilGenereltFormatMapper.kt, src/test/resources/json/pdf_generated_overgangsstønad_med_typer.json
Lagt til punktliste som mulig visningsvariant.
Tror logikken kan forbedres (linje 129-136) men venter på endringene fra @fredrikmork på feltmappen. Lager en lapp i mellomtiden.
=> Punktliste

src/main/kotlin/no/nav/familie/ef/mottak/integration/PdfKvitteringClient.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/Feltformaterer.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/FeltformatererPdfKvittering.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/FeltformatererPdfKvitteringTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/FeltformatererTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMapTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTreeWalkerTest.kt, src/test/resources/json/pdf_generated_barnetilsyn.json, src/test/resources/json/pdf_generated_barnetilsyn_med_typer.json, src/test/resources/json/pdf_generated_ettersending.json, src/test/resources/json/pdf_generated_overgangsstønad.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer.json, src/test/resources/json/pdf_generated_skolepenger.json, src/test/resources/json/pdf_generated_skolepenger_med_typer.json
Denne PR-en forbedrer funksjonen tilUtskriftsformat som formaterer en adresse til et lesbart utskriftsformat. Endringene sikrer bedre håndtering av tomme eller null verdier og tar vekk unødvendig antall linjeskift 
edit: 
har skilt pdfKvittering fra pdfGen(den gamle flyten)
=> Legg til adresse formatering

src/test/resources/json/pdf_generated_barnetilsyn_med_typer.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer.json
Språk skal være med små bokstaver ikke store, så det er likt over alt
=> Fiks språk på rett format

src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMapTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/Testdata.kt, src/test/resources/json/pdf_generated_barnetilsyn_med_typer_ny.json, src/test/resources/json/pdf_generated_overgangsstønad_med_typer_ny.json
Feilen var at objektene ble til ett objekt før og ble plassert i flere objekter slik at barn 1 og barn 2 var i både barn 1 og barn 2.
Nå er dette adskilt og fungerer som tiltenkt igjen.
Både barn og arbeidsforhold testet:
[Test-barn-og-arbeidsforhold.pdf](https://github.com/user-attachments/files/18532087/Test-barn-og-arbeidsforhold.pdf)
=> Barn og arbeidsforhold blir ikke lenger samlet i ett objekt

pom.xml, src/main/kotlin/no/nav/familie/ef/mottak/service/DittNavKafkaProducer.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTask.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTaskTest.kt, src/test/resources/application-integrationtest.yml, src/test/resources/application-local.yml
Den gamle måten på å sende brukernotifikasjon er på vei ut det er nå bedt om å migrere over til det nye topicet. Derfor har man prøvd å gjøre slik man allerede har gjort i `familie-ef-sak` og `familie-ef-iverkesett`, der man allerede har den nye implementasjonen på plass. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24075).
Migreringsguide finner du → [her](https://navikt.github.io/tms-dokumentasjon/varsler/migrere/). 
**Hovedsaklig er endringene:**
Endring av feltnavn
* `eventId` → `varselId`
* `sikkerhetsnivaa` → `sensitivitet` (`3` → `substantial`, `4` → `high`)
* `synligFremTil` → `aktivFremTil`
* `fodselsnummer` → `ident`
Deprecated felter
* `grupperingsId`
* `tidspunkt` (håndteres et …
=> Brukervarsel migrering for nytt kafka topic

pom.xml, src/test/kotlin/no/nav/familie/ef/mottak/IntegrasjonSpringRunnerTest.kt
Klarte å snike med en token validation downgrade i [PRen for uthenting av SistInnsendtSøknadDto](https://github.com/navikt/familie-ef-mottak/pull/1232). Vi endrer nå tilbake til riktig token validation bump.
=> TokenValidation oppgradering restore

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
Denne PRen prøver å fjerne deprecated work flow variabler fra bygg og deploy taskene. NAIS har satt og `identity_provider` og `project_id` deprecated og skal fjernes, da alle setter de samme verdiene her og utledes derfor automatisk av nais-plattformen nå. Workflows med disse parameterene satt vil ikke lenger virke etter 3. mars.
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24100).
Dette er en av mange PRer der denne samme endringen gjøres for repoer tilhørende enslig-forsørger.
=> Legacy - fjerne deprecated work flow variabler fra build & deploy 

src/main/kotlin/no/nav/familie/ef/mottak/service/FeltformatererPdfKvittering.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadTilFeltMap.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/FeltformatererPdfKvitteringTest.kt
Vi sender nå med språk ned til feltmapperne for å håndtere "ja" og "nei". Dette er ikke en ideell løsning på lang sikt, men det er den raskeste veien til mål akkurat nå. Denne løsningen kan leve med at den må refaktoreres senere, da utfordringen fra søknad til kvittering er at språk og tekster dikteres i ulike ledd.
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24127).
Det er fortsatt noen norske etiketter i søknadskvitteringen, som "vedlegg" osv. Dette blir tatt hensyn til, siden vi mener dette er godt nok akkurat nå.
=> Bug - språk blir sendt med til felt mappere for håndtering av "ja" og "nei"

src/main/kotlin/no/nav/familie/ef/mottak/api/PersonController.kt, src/main/kotlin/no/nav/familie/ef/mottak/api/SøknadController.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/ArkiveringService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/MappeService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/OppgaveService.kt, src/main/kotlin/no/nav/familie/ef/mottak/service/SøknadService.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/AutomatiskJournalførTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SøknadsreduksjonTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/SøknadsslettingTask.kt, src/main/kotlin/no/nav/familie/ef/mottak/task/VelgAutomatiskEllerManuellFlytTask.kt, src/test/kotlin/no/nav/familie/ef/mottak/api/SøknadControllerTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/ArkiveringServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/MappeServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/OppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceIntegrasjonTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/service/SøknadServiceTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/AutomatiskJournalførTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/FerdigstillJournalføringTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendDokumentasjonsbehovMeldingTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendPåminnelseOmDokumentasjonsbehovTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/SendSøknadMottattTilDittNavTaskTest.kt, src/test/kotlin/no/nav/familie/ef/mottak/task/VelgAutomatiskEllerManuellFlytTaskTest.kt
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24467)
- renamer fra SøknadskvitteringController til SøknadController
- renamer fra SøknadskvitteringService til SøknadService
- fjernert "søknadskvittering" fra URI til controller
=> renamet fra søknadskvitteringController til søknadController
